- hosts: loyalty_api
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
        rm get-docker.sh

    - name: Install Docker Compose
      apt:
        name: docker-compose-plugin
        state: present
        update_cache: yes

    - name: Install Caddy
      shell: |
        apt update
        apt install -y debian-keyring debian-archive-keyring apt-transport-https curl
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
        curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
        apt update
        apt install caddy

    - name: Copy Caddyfile
      copy:
        src: ../caddy/Caddyfile
        dest: /etc/caddy/Caddyfile
        mode: '0644'

    - name: Start services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - docker
        - caddy